<a href="https://colab.research.google.com/github/chohyungrae/Python-Study-/blob/master/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
#Numpy는 벡터 및 행렬 연산에 있어서 매우 편리한 기능을 제공
import numpy as np

**Numpy 배열**

- Numpy에서 배열은 동일한 타입의 값들을 가짐
- rank: 배열의 차원
- shape: 각 차원의 크기를 tuple로 표시한 것
- Numpy에서 배열의 타입은 ndarray

**Numpy 배열 생성**

===> 파이썬의 리스트를 사용하는 방법

In [7]:
#array()함수의 인자로 리스트를 넣어 생성

list1 = [1,2,3,4]
a = np.array(list1)
print(a)
print(a.shape)

[1 2 3 4]
(4,)


===> Numpy에서 제공하는 함수를 사용하는 방법


In [10]:
#zeros(): 배열에 모두 0을 집어 넣음

aa = np.zeros((2,2))
aa

array([[0., 0.],
       [0., 0.]])

In [11]:
type(aa)

numpy.ndarray

In [12]:
#ones(): 배열에 모두 1을 집어 넣음

aa = np.ones((2,3))
aa

array([[1., 1., 1.],
       [1., 1., 1.]])

In [13]:
#full(): 배열에 사용자가 지정한 값을 넣음

aa=np.full((2,3), 10)
aa

array([[10, 10, 10],
       [10, 10, 10]])

In [14]:
#eye(): 대각선으로는 1이고 나머지는 0인 2차원 배열을 생성
aa=np.eye(3)
aa

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
#reshape(): 다차원으로 변형하는 함수

aa=np.array(range(20)).reshape((5,4)) #range(n): 0~n-1까지의 숫자를 생성하는 함수
aa

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [16]:
aa=np.array(range(15)).reshape((3,5))
aa

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [8]:
#array라는 단위로 데이터를 관리하며 이에 대해 연산을 수행
#array=행렬
a=np.arange(21)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [9]:
#reshape 모양을 행렬로 바꾼다
b=a.reshape(3,7)
b

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20]])

In [ ]:
#shape이란 array의 형태(크기)를 나타냄
a.shape

(21,)

In [ ]:
#array의 자료형 확인
a.dtype

dtype('int64')

In [ ]:
arr4=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
arr4

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
arr4.shape

(4, 3)

# **numpy shape**

numpy에서는 해당 array의 크기를 알 수 있다.

shape 을 확인함으로써 몇개의 데이터가 있는지, 몇 차원으로 존재하는지 등을 확인할 수 있다.

(5,)의 경우는 1차원의 데이터이며 총 5라는 크기를 갖고 있음을 뜻한다.

위의 arr4.shape의 결과(4,3)은, 2차원의 데이터이며 4 * 3 크기를 갖고 있는 array 이다.

# **numpy 자료형**

arr1이나 arr2는 int64라는 자료형을 갖는 것에 반해 arr3는 float64라는 자료형을 갖는다.

이는 arr3내부 데이터를 살펴보면 3.5라는 실수형 데이터를 갖기 때문임을 알 수 있다.

numpy에서 사용되는 자료형은 아래와 같다. (자료형 뒤에 붙는 숫자는 몇 비트 크기인지를 의미한다.)

- 부호가 있는 정수 int(8, 16, 32, 64)
- 부호가 없는 정수 uint(8 ,16, 32, 54)
- 실수 float(16, 32, 64, 128)
- 복소수 complex(64, 128, 256)
- 불리언 bool
- 문자열 string_
- 파이썬 오프젝트 object
- 유니코드 unicode_



**np.zeros(), np.ones(), np.arange() 함수**

- numpy에서 array를 정의할 때 사용되는 함수들이다.


In [20]:
a=np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
#np.zeros() 함수는 인자로 받는 크기만큼, 모든요소가 0인 array를 만든다.

a=np.zeros((3,5))
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [23]:
#np.ones() 함수는 인자로 받는 크기만큼, 모든요소가 1인 array를 만든다.
a=np.ones(9)
a

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [24]:
a=np.ones((2,10))
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [26]:
# np.arange() 함수는 인자로 받는 값 만큼 1씩 증가하는 1차원 array를 만든다.
# 이때 하나의 인자만 입력하면 0 ~ 입력한 인자, 값 만큼의 크기를 가진다.

a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
a=np.arange(3,10)
a

array([3, 4, 5, 6, 7, 8, 9])

**Array 연산**

기본적으로 numpy에서 연산을 할때는 크기가 서로 동일한 array 끼리 연산이 진행된다.

이때 같은 위치에 있는 요소들 끼리 연산이 진행된다.


In [28]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
arr1.shape

(2, 3)

In [30]:
arr2 = np.array([[10,11,12],[13,14,15]])
arr2

array([[10, 11, 12],
       [13, 14, 15]])

In [31]:
arr2.shape

(2, 3)

In [32]:
#array 덧셈

arr1 + arr2

array([[11, 13, 15],
       [17, 19, 21]])

In [33]:
#array 뺄셈

arr1 - arr2


array([[-9, -9, -9],
       [-9, -9, -9]])

In [34]:
#array 곱셈
arr1 * arr2

array([[10, 22, 36],
       [52, 70, 90]])

In [35]:
#array 나눗셈
arr1 / arr2

array([[0.1       , 0.18181818, 0.25      ],
       [0.30769231, 0.35714286, 0.4       ]])

# **array의 브로드 캐스트**
array가 같은 크기를 가져야 서로 연산이 가능하다고 했지만,

numpy에서는 브로드캐스트라는 기능을 제공한다.

**브로드캐스트란, 서로 크기가 다른 array가 연산이 가능하게끔 하는 것이다.**

In [37]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
arr1 * 10

array([[10, 20, 30],
       [40, 50, 60]])

In [40]:
#요소에 대해 제곱처리
arr1 ** 2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [ ]:
#Array 인덱싱
numpy에서 사용되는 인덱싱은 기본적으로 python 인덱싱과 동일하다.

이때, python에서와 같이 1번째로 시작하는 것이 아니라 0번째로 시작하는 것에 주의한다.



출처: https://doorbw.tistory.com/171 [Tigercow.Door]

**Array 인덱싱**

numpy에서 사용되는 인덱싱은 기본적으로 python 인덱싱과 동일하다.

이때, python에서와 같이 1번째로 시작하는 것이 아니라 0번째로 시작하는 것에 주의한다.


In [41]:
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
# 0번째 요소
arr1[0]

0

In [43]:
# 3번째 요소
arr1[3]

3

In [44]:
# 3번째 요소부터 8번째 요소
arr1[3:9]

array([3, 4, 5, 6, 7, 8])

In [45]:
arr1[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
#1차원이 아닌 그 이상의 차원에서도 인덱싱이 가능하다.

arr2 = np.array([[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12]])
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [47]:
# 2차원의 array에서 인덱싱을 하기 위해선 2개의 인자를 입력해야 합니다.
arr2[0,0]

1

In [48]:
# 2행의 모든 요소 꺼내기
arr2[2,:]

array([ 9, 10, 11, 12])

In [49]:
# 2행의 3번째 요소 꺼내기
arr2[2,3]

12

In [50]:
# 모든 열의 3번째 요소 꺼내기
arr2[:,3]

array([ 4,  8, 12])

# **Array boolean 인덱싱(마스크)**
다차원의 인덱싱을 응용하여 boolean 인덱싱을 할 수 있다.

해당 기능은 주로 마스크라고 이야기하는데, boolean인덱싱을 통해 만들어낸 array를 통해

우리가 원하는 행 또는 열의 값만 뽑아낼 수 있다.

즉, 마스크처럼 우리가 가리고 싶은 부분은 가리고, 원하는 요소만 꺼낼 수 있다.


In [51]:
names = np.array(['Beomwoo','Beomwoo','Kim','Joan','Lee','Beomwoo','Park','Beomwoo'])
names

array(['Beomwoo', 'Beomwoo', 'Kim', 'Joan', 'Lee', 'Beomwoo', 'Park',
       'Beomwoo'], dtype='<U7')

In [52]:
names.shape

(8,)

In [53]:
# np.random.randn() 함수는 기대값이 0이고, 표준편차가 1인 가우시안 정규 분포를 따르는 난수를 발생시키는 함수이다.
# 이 외에도 0~1의 난수를 발생시키는 np.random.rand() 함수
data = np.random.randn(8,4)
data

array([[ 0.52135407,  1.32763546, -1.0227306 ,  0.39790141],
       [-0.14306771, -0.7824314 ,  0.98242483, -0.43623689],
       [ 1.18811829, -1.33501556, -0.22249927, -0.08306698],
       [-0.41364264, -1.26159614, -0.62691431, -1.86756415],
       [-0.34013395, -0.39499934, -0.85260826, -0.21046281],
       [ 1.16530248, -1.29942624, -0.06438028, -0.59149485],
       [ 1.90708004,  0.0507653 ,  0.50320838, -0.171268  ],
       [-0.08906598,  0.66861701,  0.07065355, -0.47539059]])

In [56]:
# 0~1의 난수를 발생시키는 np.random.rand() 함수

data = np.random.rand(8,4)
data

array([[0.54522299, 0.41415995, 0.5921561 , 0.06559438],
       [0.00705714, 0.32452021, 0.81114118, 0.02037183],
       [0.86312832, 0.71529513, 0.33514094, 0.3699738 ],
       [0.34296086, 0.32258367, 0.29359095, 0.73713412],
       [0.93483423, 0.56938745, 0.74196459, 0.58295272],
       [0.01041607, 0.77145394, 0.22086363, 0.39618731],
       [0.34925009, 0.47412236, 0.87218262, 0.52870925],
       [0.32460371, 0.80648987, 0.98553319, 0.94480423]])

In [57]:
data.shape

(8, 4)

위와 같은 names와 data라는 array가 있다.

이때, names의 각 요소가 data의 각 행과 연결된다고 가정해보자.

그리고 이 때, names가 Beomwoo인 행의 data만 보고 싶을 때 다음과 같이 마스크를 사용한다.

In [59]:
# 요소가 Beomwoo인 항목에 대한 mask 생성

names = np.array(['Beomwoo','Beomwoo','Kim','Joan','Lee','Beomwoo','Park','Beomwoo'])
names
names_Beomwoo_mask = (names == 'Beomwoo')
names_Beomwoo_mask

array([ True,  True, False, False, False,  True, False,  True])

In [60]:
'''
요소가 Beomwoo인 것은 0번째, 1번째, 5번째, 7번째 이므로
data에서 0,1,5,7행의 모든 요소를 꺼내와야 한다.
이를 위해 요소가 Beomwoo인 것에 대한 boolean 값을 가지는 mask를 만들었고
마스크를 인덱싱에 응용하여 data의 0,1,5,7행을 꺼냈다.
'''
data[names_Beomwoo_mask,:]


array([[0.54522299, 0.41415995, 0.5921561 , 0.06559438],
       [0.00705714, 0.32452021, 0.81114118, 0.02037183],
       [0.01041607, 0.77145394, 0.22086363, 0.39618731],
       [0.32460371, 0.80648987, 0.98553319, 0.94480423]])

In [62]:
#numpy 참조 사이트 <=  이어서 하기
#https://doorbw.tistory.com/171