<a href="https://colab.research.google.com/github/chohyungrae/Python-Study-/blob/master/numpy31%EC%B0%A8%EC%8B%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
#Numpy는 벡터 및 행렬 연산에 있어서 매우 편리한 기능을 제공
import numpy as np

In [8]:
#array라는 단위로 데이터를 관리하며 이에 대해 연산을 수행
#array=행렬
a=np.arange(21)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [5]:
#reshape 모양을 행렬로 바꾼다
b=a.reshape(3,7)
b

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20]])

In [9]:
#shape이란 array의 형태(크기)를 나타냄
a.shape

(21,)

In [10]:
#array의 자료형 확인
a.dtype

dtype('int64')

In [13]:
arr4=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
arr4

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [14]:
arr4.shape

(4, 3)