<a href="https://colab.research.google.com/github/chohyungrae/Python-Study-/blob/master/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [63]:
import numpy as np

In [64]:
a = np.arange(21)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [65]:
b = a. reshape(3,7)
b

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20]])

In [66]:
a.shape

(21,)

In [67]:
b.shape

(3, 7)

In [68]:
a.ndim #차원

1

In [69]:
b.ndim

2

In [70]:
a.dtype

dtype('int64')

In [71]:
c = np.array([(1,2,3),(4,5.5,6)])
c

array([[1. , 2. , 3. ],
       [4. , 5.5, 6. ]])

In [72]:
c.dtype

dtype('float64')

In [73]:
np.zeros(((3,5)))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [74]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [75]:
np.full((3,3), 777.7) #특정숫자 넣기

array([[777.7, 777.7, 777.7],
       [777.7, 777.7, 777.7],
       [777.7, 777.7, 777.7]])

In [76]:
np.arange(1,20,2) #1부터 20까지 2개씩 띄워서

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [77]:
np.linspace(0,10,2)#시작과 끝점을 정해주고 2개를 써라

array([ 0., 10.])

In [78]:
e = np.array([1,2,3,4])
f = np.arange(4)
f

array([0, 1, 2, 3])

In [79]:
e*f

array([ 0,  2,  6, 12])

In [80]:
e-f

array([1, 1, 1, 1])

In [81]:
e*3

array([ 3,  6,  9, 12])

In [82]:
e**3

array([ 1,  8, 27, 64])

In [83]:
g = np.arange(9).reshape(3,3)
h = np.arange(9).reshape(3,3)+1
h

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [84]:
g

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [85]:
g*h

array([[ 0,  2,  6],
       [12, 20, 30],
       [42, 56, 72]])

In [86]:
g**h #지수

array([[        0,         1,         8],
       [       81,      1024,     15625],
       [   279936,   5764801, 134217728]])

In [87]:
g**h

array([[        0,         1,         8],
       [       81,      1024,     15625],
       [   279936,   5764801, 134217728]])

In [88]:
g>3

array([[False, False, False],
       [False,  True,  True],
       [ True,  True,  True]])

In [89]:
i = np.array([[[[1,2],[3,4]]]], dtype = np.float64)
i

array([[[[1., 2.],
         [3., 4.]]]])

In [90]:
i.dtype

dtype('float64')

In [91]:
i.ndim

4

In [92]:
#랜덤
k = np.random.random((5,2))
k

array([[0.81780768, 0.11784869],
       [0.60023242, 0.66024947],
       [0.49334789, 0.65977524],
       [0.07808846, 0.89466533],
       [0.62856913, 0.35353395]])

In [93]:
k.min()

0.07808845764795536

In [94]:
k.max()

0.8946653259486812

In [95]:
k.mean()

0.5304118250589575

In [96]:
k.sum()

5.304118250589575

In [97]:
k.sum(axis=0)

array([2.61804557, 2.68607268])

In [98]:
k.sum(axis=1)

array([0.93565637, 1.26048189, 1.15312313, 0.97275378, 0.98210308])

In [99]:
np.exp(k)

array([[2.26552762, 1.12507387],
       [1.82254235, 1.93527506],
       [1.63779019, 1.93435752],
       [1.0812183 , 2.44651687],
       [1.87492588, 1.42409133]])

In [100]:
np.add(k,k)

array([[1.63561535, 0.23569739],
       [1.20046484, 1.32049893],
       [0.98669578, 1.31955048],
       [0.15617692, 1.78933065],
       [1.25713825, 0.7070679 ]])

In [101]:
np.sin(k) #싸인 값

array([[0.72964842, 0.1175761 ],
       [0.56483428, 0.61331391],
       [0.4735772 , 0.61293928],
       [0.07800912, 0.77999969],
       [0.58798797, 0.34621536]])

In [102]:
np.sin(k[0,0])

0.7296484234748671

In [103]:
k

array([[0.81780768, 0.11784869],
       [0.60023242, 0.66024947],
       [0.49334789, 0.65977524],
       [0.07808846, 0.89466533],
       [0.62856913, 0.35353395]])

In [104]:
k[3]

array([0.07808846, 0.89466533])

In [105]:
k[3:]

array([[0.07808846, 0.89466533],
       [0.62856913, 0.35353395]])

In [106]:
k[:3,:1]

array([[0.81780768],
       [0.60023242],
       [0.49334789]])

In [107]:
k[:3]

array([[0.81780768, 0.11784869],
       [0.60023242, 0.66024947],
       [0.49334789, 0.65977524]])

In [108]:
k

array([[0.81780768, 0.11784869],
       [0.60023242, 0.66024947],
       [0.49334789, 0.65977524],
       [0.07808846, 0.89466533],
       [0.62856913, 0.35353395]])

In [109]:
k[:3,1]

array([0.11784869, 0.66024947, 0.65977524])

In [110]:
k[0,1]

0.11784869484419647

In [111]:
k[0,1] = 3.333 #위치에 있는 값 바꾸기
k

array([[0.81780768, 3.333     ],
       [0.60023242, 0.66024947],
       [0.49334789, 0.65977524],
       [0.07808846, 0.89466533],
       [0.62856913, 0.35353395]])

In [112]:
k[-1]

array([0.62856913, 0.35353395])

In [113]:
k

array([[0.81780768, 3.333     ],
       [0.60023242, 0.66024947],
       [0.49334789, 0.65977524],
       [0.07808846, 0.89466533],
       [0.62856913, 0.35353395]])

In [114]:
k[-3]

array([0.49334789, 0.65977524])

In [115]:
k[:-1]

array([[0.81780768, 3.333     ],
       [0.60023242, 0.66024947],
       [0.49334789, 0.65977524],
       [0.07808846, 0.89466533]])

In [116]:
k[:-1,-2]

array([0.81780768, 0.60023242, 0.49334789, 0.07808846])

In [117]:
for i in k[1:3]: 
  print(i)

[0.60023242 0.66024947]
[0.49334789 0.65977524]


In [118]:
#0부터 9까지 랜덤하게 초기화 된 배열
array4 = np.random.randint(0,10,(3,3))
print(array4)

[[1 7 9]
 [4 8 7]
 [4 2 0]]


In [119]:
#평균이 0이고, 표준편차가 1인 표준정규분포 배열
array5 = np.random.normal(0,1,(3,3))
print(array5)

[[-1.85832013 -0.5397146  -0.67716046]
 [ 0.42005238 -0.57808427  0.53851193]
 [-1.63253463 -0.56339489  1.49509429]]


In [120]:
#배열을 바꿈
array1 = np.array([1,2,3,4])
array2 = array1.reshape((2,2))
print(array2)

[[1 2]
 [3 4]]


In [123]:
array = np.arange(8).reshape(2,4)
left, right = np.split(array, [2], axis=1)
print(left.shape)
print(right.shape)

(2, 2)
(2, 2)
