<a href="https://colab.research.google.com/github/chohyungrae/Python-Study-/blob/master/python_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a = np.arange(21)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [4]:
b = a. reshape(3,7)
b

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20]])

In [5]:
a.shape

(21,)

In [6]:
b.shape

(3, 7)

In [8]:
a.ndim #차원

1

In [9]:
b.ndim

2

In [10]:
a.dtype

dtype('int64')

In [14]:
c = np.array([(1,2,3),(4,5.5,6)])
c

array([[1. , 2. , 3. ],
       [4. , 5.5, 6. ]])

In [15]:
c.dtype

dtype('float64')

In [17]:
np.zeros(((3,5)))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
np.full((3,3), 777.7) #특정숫자 넣기

array([[777.7, 777.7, 777.7],
       [777.7, 777.7, 777.7],
       [777.7, 777.7, 777.7]])

In [22]:
np.arange(1,20,2) #1부터 20까지 2개씩 띄워서

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [24]:
np.linspace(0,10,2)#시작과 끝점을 정해주고 2개를 써라

array([ 0., 10.])

In [25]:
e = np.array([1,2,3,4])
f = np.arange(4)
f

array([0, 1, 2, 3])

In [26]:
e*f

array([ 0,  2,  6, 12])

In [27]:
e-f

array([1, 1, 1, 1])

In [28]:
e*3

array([ 3,  6,  9, 12])

In [29]:
e**3

array([ 1,  8, 27, 64])

In [30]:
g = np.arange(9).reshape(3,3)
h = np.arange(9).reshape(3,3)+1
h

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
g

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [32]:
g*h

array([[ 0,  2,  6],
       [12, 20, 30],
       [42, 56, 72]])

In [33]:
g**h #지수

array([[        0,         1,         8],
       [       81,      1024,     15625],
       [   279936,   5764801, 134217728]])

In [34]:
g**h

array([[        0,         1,         8],
       [       81,      1024,     15625],
       [   279936,   5764801, 134217728]])

In [35]:
g>3

array([[False, False, False],
       [False,  True,  True],
       [ True,  True,  True]])

In [36]:
i = np.array([[[[1,2],[3,4]]]], dtype = np.float64)
i

array([[[[1., 2.],
         [3., 4.]]]])

In [37]:
i.dtype

dtype('float64')

In [38]:
i.ndim

4

In [52]:
#랜덤
k = np.random.random((5,2))
k

array([[0.95860656, 0.13160745],
       [0.70420248, 0.85631535],
       [0.72764623, 0.41345459],
       [0.99724668, 0.25101778],
       [0.24889914, 0.28755935]])

In [55]:
k.min()

0.1316074460278649

In [56]:
k.max()

0.9972466798584038

In [57]:
k.mean()

0.5576555594244663

In [58]:
k.sum()

5.576555594244663

In [59]:
k.sum(axis=0)

array([3.63660108, 1.93995452])

In [60]:
k.sum(axis=1)

array([1.090214  , 1.56051783, 1.14110082, 1.24826446, 0.53645849])

In [61]:
np.exp(k)

array([[2.60805975, 1.14066046],
       [2.02223326, 2.35446931],
       [2.07020209, 1.51203222],
       [2.71080782, 1.28533294],
       [1.28261266, 1.33316971]])

In [62]:
np.add(k,k)

array([[1.91721311, 0.26321489],
       [1.40840495, 1.71263071],
       [1.45529246, 0.82690918],
       [1.99449336, 0.50203556],
       [0.49779828, 0.57511869]])

In [64]:
np.sin(k) #싸인 값

array([[0.8183916 , 0.13122786],
       [0.64742622, 0.75543342],
       [0.66511382, 0.40177522],
       [0.83998017, 0.24838997],
       [0.24633717, 0.28361263]])

In [65]:
np.sin(k[0,0])

0.8183916048562659

In [66]:
k

array([[0.95860656, 0.13160745],
       [0.70420248, 0.85631535],
       [0.72764623, 0.41345459],
       [0.99724668, 0.25101778],
       [0.24889914, 0.28755935]])

In [67]:
k[3]

array([0.99724668, 0.25101778])

In [68]:
k[3:]

array([[0.99724668, 0.25101778],
       [0.24889914, 0.28755935]])

In [69]:
k[:3,:1]

array([[0.95860656],
       [0.70420248],
       [0.72764623]])

In [70]:
k[:3]

array([[0.95860656, 0.13160745],
       [0.70420248, 0.85631535],
       [0.72764623, 0.41345459]])

In [72]:
k

array([[0.95860656, 0.13160745],
       [0.70420248, 0.85631535],
       [0.72764623, 0.41345459],
       [0.99724668, 0.25101778],
       [0.24889914, 0.28755935]])

In [73]:
k[:3,1]

array([0.13160745, 0.85631535, 0.41345459])

In [74]:
k[0,1]

0.1316074460278649

In [76]:
k[0,1] = 3.333 #위치에 있는 값 바꾸기
k

array([[0.95860656, 3.333     ],
       [0.70420248, 0.85631535],
       [0.72764623, 0.41345459],
       [0.99724668, 0.25101778],
       [0.24889914, 0.28755935]])

In [77]:
k[-1]

array([0.24889914, 0.28755935])

In [78]:
k

array([[0.95860656, 3.333     ],
       [0.70420248, 0.85631535],
       [0.72764623, 0.41345459],
       [0.99724668, 0.25101778],
       [0.24889914, 0.28755935]])

In [79]:
k[-3]

array([0.72764623, 0.41345459])

In [80]:
k[:-1]

array([[0.95860656, 3.333     ],
       [0.70420248, 0.85631535],
       [0.72764623, 0.41345459],
       [0.99724668, 0.25101778]])

In [81]:
k[:-1,-2]

array([0.95860656, 0.70420248, 0.72764623, 0.99724668])

In [82]:
for i in k[1:3]: 
  print(i)

[0.70420248 0.85631535]
[0.72764623 0.41345459]
